spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:h2test
    schema: classpath:schema.sql
    data: classpath:data.sql
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
